---
name: 101种食物分类
author: jiayi
description: 101种食物分类
topic: 101种食物分类
algorithm: VGG
language: python3
virtualenv: flyai_env/bin/
framework: Pytorch

data:
  id: Food
  name: 101种食物分类数据集
  category: image

model:
  processor: Processor
  input_x: input_x
  output_x: output_x
  input_y: input_y
  output_y: output_y
  input:
    columns:
      - name: image_path
        type: string
    to_type: float
    to_shape: [-1,448, 448, 3]
  output:
    columns:
      - name: labels
        type: int
    to_type: float
    to_shape: [-1,101]







servers:
  - id: flyai
    url: https://flyai.com
...